<div class="container mt-5 tnc-content">
    <h1>User Terms & Conditions</h1>
    <p>These terms of use ("Terms of Use") mandate the terms on which users ("You" or "Your" or "Yourself" or "Users") interested in browsing or availing Pantryo Services (defined below), and accessing the platform www.pantryo.in and the mobile application owned and operated by Gizmmo Alchemy(“Pantryo”) collectively referred to as, the "Platform" connects with the merchants registered on the Platform ("Tied-up Merchants"), merchants not registered on the Platform ("Non- Merchants") (together hereinafter referred to as "Merchants") and with delivery partners ("Delivery Partners") to avail the Pantryo Services.
        Please read the Terms of Use carefully before using the Platform or registering on the Platform or accessing any material or information through the Platform. By clicking on the "I Accept" button, You accept this Terms of Use and agree to be legally bound by the same.
        Use of and access to the Platform is offered to You upon the condition of acceptance of all the terms, conditions and notices contained in this Terms of Use and Privacy Policy, along with any amendments made by Pantryo at its sole discretion and posted on the Platform from time to time.
    </p>
    <p>For the purposes of these Terms of Use, the term 'Pantryo' or 'Us' or 'We' refers to Gizmmo Alchemy. The term 'You' refers to the user or visitor of the Website and/or App. When You use our services, You will be subject to the terms, guidelines and policies applicable to such service and as set forth in these Terms of Use. As long as you comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use our Platforms and services.</p>

    <h2>PART A - GENERAL TERMS RELATING TO PANTRYO SERVICES</h2>

    <h3>1. Registration:</h3>
    <p>a. You shall be permitted to access the Platform, avail the Pantryo Services and connect with Merchants and Delivery Partners on the Platform only upon creating an Account (as defined below) and obtaining a registration on the Platform. Your ability to continue using the Platform, Pantryo Services is subject to Your continued registration on the Platform. You will be required to enter Your personal information including your name, contact details, address, valid phone number while registering on the Platform.</p>
    <p>b. As a part of the registration, You may be required to undertake a verification process to verify Your personal information and setting up the Account.</p>
    <p>c. Pantryo shall have the right to display the information, feedback, ratings, reviews etc. provided by You on the Platform. You agree and accept that as on the date of Your registration on the Platform, the information provided by You is complete, accurate and up-to-date. In the event of any change to such information, You shall be required to promptly inform Pantryo of the same, in writing, at least 1 (one) week prior to the date on which such change shall take effect. You acknowledge and accept that Pantryo has not independently verified the information provided by You. Pantryo shall in no way be responsible or liable for the accuracy or completeness of any information provided by You. If You provide any information that is untrue, inaccurate, not current or incomplete, or Pantryo has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, Pantryo reserves the right to suspend or terminate Your Account (defined below) and refuse any and all current or future use of the Platform (or any portion thereof) at any time.</p>

    <h3>2. Pantryo Services:</h3>
    <p>a. The Platform provides You with the following services ("Pantryo Services"):</p>
    <ol>
        <li>It allows You to connect with Merchants and Delivery Partners;</li>
        <li>It allows You to view the items/services ("Items") listed on the Platform by the Merchants;</li>
        <li>It allows You to purchase Item(s) from the Merchants listed on the Platform and allows You to get the Items delivered to You through Delivery Partners ("Purchase Services");</li>
        <li>It allows You to purchase Items from Non- Merchants and get the same delivered to You by the Delivery Partners ("Delivery Services");</li>
        <li>It allows you to pick up- and drop off packages from 1 (one) location to the other through the Delivery Partner ("Pick Up and Drop Off Services");</li>
        <li>It allows You to give ratings, write comments and reviews about Delivery Partners and Merchants;</li>
        <li>It facilitates improvement in the quality of the services provided by Pantryo on the Platform based on User ratings, reviews and feedbacks provided on the Platform.</li>
    </ol>
    <p>b. Once the Delivery Services/ Purchase Services/Pick-Up and Drop Off Services have been completed or delivered, as the case may be, you shall promptly notify the same on the Platform.</p>
    <p>c. Pantryo may, at its absolute sole discretion, add, modify, upgrade, extend, withdraw or alienate any of the Pantryo Services listed above from time to time. Pantryo does not provide any guarantee to You that the Pantryo Services will be made available to You at all times.</p>
    <p>d. You hereby agree and acknowledge that Pantryo is only a facilitator between You, the Merchants and Delivery Partners (as the case maybe) and Pantryo only provides You with access to the Platform to connect with Merchants and Delivery Partners for You to initiate transactions on the Platform. You hereby agree and acknowledge that Pantryo will not be a party to any of the transactions that are initiated by You through the Platform and Pantryo shall not be liable in any manner or incur any liability with respect to the services performed by the Merchants or the Delivery Partners, as the case may be. Further, you hereby agree and acknowledge that Pantryo shall not be liable for the conduct, acts and omissions of the Merchants (including their employees and consultants) and Delivery Partners in the course of providing their services to You, or for any loss or damage to the Item or otherwise caused to You as a consequence of or in relation to the services being provided to You by the Merchants or the Delivery Partner, as the case may be.</p>
    <p>e. In case of Purchase Services, it is the duty of the Tied-Up Merchants to share the updated Item list along with its prices on the Platform. Pantryo shall not be responsible for any inaccurate Item listing on the Platform. Further, You hereby agree and acknowledge that for certain Items (Items that are perishable in nature or Item whose price varies periodically), it may not be possible for the Tied-Up Merchants to list out the exact price or prices of such Items on the Platform. The above shall also be applicable to the provision of Purchase Services.</p>
    <p>f. You shall not initiate any transaction for any Item on the Platform which is illegal, immoral, unethical, unlawful, unsafe, contains harmful substance and is in violation of this Terms of Use and applicable laws. You specifically agree that You shall not initiate any transaction on the Platform for the purchase or delivery of any alcoholic beverages, narcotic drug or psychotropic substance, etc. Further, You hereby acknowledge and agree that Pantryo shall not be liable for any indirect, direct damage or loss, cost, expense incurred by You in relation to the transactions initiated by You on the Platform.</p>
    <p>g. Pantryo does not check or verify the packages that are being delivered to You by the Delivery Partner, and therefore Pantryo shall have no liability with respect to the same. However, if it comes to the knowledge of Pantryo that You have packaged any illegal or dangerous substance to deliver any illegal or dangerous substance, Pantryo shall have the right to report You to the government authorities and take other appropriate legal actions against You.</p>
    <p>h. You hereby acknowledge that Pantryo shall not be liable for any damages of any kind arising from Your use of the Pantryo Services, including, but not limited to direct, indirect, incidental, punitive, and consequential damages.</p>
    <p>i. Pantryo shall be entitled at any time without giving any reason terminate Your request for any Pantryo Service.</p>
    <p>j. You hereby agree that Pantryo shall not be liable for any conduct or misbehaviour or actions of Delivery Partner with respect to any transactions initiated on the Platform. Further, You agree that Pantryo has no control over the Items provided to You by the Merchants and therefore, Pantryo shall not incur any liability with respect to such Items. However, keeping in mind the interests of the Users, We have informed our Merchants to ensure that Items are packaged properly to avoid any form of spillage or damage to the Item or any issues related to packaging</p>
    <p>k. If a transaction initiated by You on the Platform cannot be completed, Pantryo shall notify You on the Platform.</p>
    <p>l. You agree to provide as much information as possible on the Platform with respect to the Items You wish to purchase, using the Platform.</p>
    <p>m. Pantryo shall use Your location based information that is captured by Pantryo through global positioning system when You are using Your mobile device to request a Pantryo Service on its mobile-app. Such location based information shall be used by Pantryo only to facilitate and improve the Pantryo Services being offered to You.</p>
    <P>n. You understand and acknowledge that Pantryo by itself does not sell or provide any such Items. Pantryo is not responsible for the quality, merchantability or fitness of such Items. Accordingly, in the event of any grievances arising from the transaction initiated by You on the Platform pertaining to purchase or sale of any product from any Merchant, You may contact Pantryo support for routing. your grievances to the Merchant through the Platform.</P>
    <p>o. You hereby acknowledge that if You have any complaint with respect to the Pantryo Services, You will first inform Pantryo in writing within 24 (twenty four) hours of using such Pantryo Services</p>

    <h3>3. User Information</h3>
</div>